version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: ticket-manager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5435:5432'
